FrunutStock.Web/Areas/Stock/Controllers/CountriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FrunutStock.Data;
using FrunutStock.Model.Models;

namespace FrunutStock.Web.Areas.Stock.Controllers
{
    public class CountriesController : Controller
    {
        private FrunutStockEntities db = new FrunutStockEntities();

        // GET: Stock/Countries
        public ActionResult Index()
        {
            return View(db.Countries.ToList());
        }

        // GET: Stock/Countries/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Country country = db.Countries.Find(id);
            if (country == null)
            {
                return HttpNotFound();
            }
            return View(country);
        }

        // GET: Stock/Countries/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Stock/Countries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,AddedDate,ModifiedDate,UserName")] Country country)
        {
            if (ModelState.IsValid)
            {
                db.Countries.Add(country);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(country);
        }

        // GET: Stock/Countries/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Country country = db.Countries.Find(id);
            if (country == null)
            {
                return HttpNotFound();
            }
            return View(country);
        }

        // POST: Stock/Countries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,AddedDate,ModifiedDate,UserName")] Country country)
        {
            if (ModelState.IsValid)
            {
                db.Entry(country).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(country);
        }

        // GET: Stock/Countries/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Country country = db.Countries.Find(id);
            if (country == null)
            {
                return HttpNotFound();
            }
            return View(country);
        }

        // POST: Stock/Countries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Country country = db.Countries.Find(id);
            db.Countries.Remove(country);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FrunutStock.Web/Areas/Stock/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FrunutStock.Data;
using FrunutStock.Model.Models;

namespace FrunutStock.Web.Areas.Stock.Controllers
{
    public class ItemsController : Controller
    {
        private FrunutStockEntities db = new FrunutStockEntities();

        // GET: Stock/Items
        public ActionResult Index()
        {
            var items = db.Items.Include(i => i.Country).Include(i => i.ItemGroup);
            return View(items.ToList());
        }

        // GET: Stock/Items/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: Stock/Items/Create
        public ActionResult Create()
        {
            ViewBag.CountryID = new SelectList(db.Countries, "ID", "Name");
            ViewBag.ItemGroupID = new SelectList(db.ItemGroups, "ID", "Name");
            return View();
        }

        // POST: Stock/Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Description,MinimumPrice,BoxWeight,TotalBoxesOnHand,TotalWeightOnHand,TotalBoxesReserved,TotalWeightReserved,ItemGroupID,CountryID,AddedDate,ModifiedDate,UserName")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.Items.Add(item);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CountryID = new SelectList(db.Countries, "ID", "Name", item.CountryID);
            ViewBag.ItemGroupID = new SelectList(db.ItemGroups, "ID", "Name", item.ItemGroupID);
            return View(item);
        }

        // GET: Stock/Items/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            ViewBag.CountryID = new SelectList(db.Countries, "ID", "Name", item.CountryID);
            ViewBag.ItemGroupID = new SelectList(db.ItemGroups, "ID", "Name", item.ItemGroupID);
            return View(item);
        }

        // POST: Stock/Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Description,MinimumPrice,BoxWeight,TotalBoxesOnHand,TotalWeightOnHand,TotalBoxesReserved,TotalWeightReserved,ItemGroupID,CountryID,AddedDate,ModifiedDate,UserName")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CountryID = new SelectList(db.Countries, "ID", "Name", item.CountryID);
            ViewBag.ItemGroupID = new SelectList(db.ItemGroups, "ID", "Name", item.ItemGroupID);
            return View(item);
        }

        // GET: Stock/Items/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Stock/Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Item item = db.Items.Find(id);
            db.Items.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FrunutStock.Web/Areas/Stock/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <!-- Bootstrap -->
    @Styles.Render("~/css/bootstrap.css")
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/
    html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/
    respond.min.js"></script>
    <![endif]-->
</head>
<body>

    <nav id="myNavbar" class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Frunut", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="nav navbar-nav">
                <li class="active">
                    @Html.ActionLink("Stock", "Index", "Home", new { area = "Stock" }, null)
                </li>
                <li class="active">
                    @Html.ActionLink("Item country", "Index", "Countries", new { area = "Stock" }, null)
                </li>
                <li class="active">
                    @Html.ActionLink("Item group", "Index", "ItemGroups", new { area = "Stock" }, null)
                </li>
                <li class="active">
                    @Html.ActionLink("Item", "Index", "Items", new { area = "Stock" }, null)
                </li>
                <li class="active">
                    @Html.ActionLink("Add item to warehouse ", "Index", "ReceiveItems", new { area = "Stock" }, null)
                </li>
                <li class="active">
                    @Html.ActionLink("Warehouse", "Index", "Warehouses", new { area = "Stock" }, null)
                </li>
                <li class="active">
                    @Html.ActionLink("Items in Warehouse", "Index", "ItemWarehouses", new { area = "Stock" }, null)
                </li>
                <li>
                    <p>
                        <a href="@Url.Action("logout", "auth")"><img src="~/Content/Images/ShutDown.jpg" width="25px" height="25px" alt="Log out" style="vertical-align:middle" /> </a>
                    </p>
                </li>
            </ul>
        </div>
    </nav>
    @RenderBody()
    
   
    @Scripts.Render("~/js/bootstrap.js")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>